#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    Aug 02, 2018 12:27:57 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_4_0 .top37.tNo38.pg0 
    set site_4_0 $site_4_0
    set site_4_1 .top37.tNo38.pg1 
    set site_4_0 $site_4_1
    set site_5_0 $site_4_0.tLa37
    set site_5_0 $site_4_0.tLa38
    set site_5_0 $site_4_0.tLa39
    set site_4_2 .top37.tNo38.pg2 
    set site_4_0 $site_4_2
    set site_5_0 $site_4_0.tLa37
    set site_5_0 $site_4_0.cpd43
    set site_4_3 .top37.tNo38.pg3 
    set site_4_0 $site_4_3
    set site_5_0 $site_4_0.tLa37
    set site_5_0 $site_4_0.tLa38
    set site_5_0 $site_4_0.tLa39
    set site_5_0 $site_4_0.tLa46
    set site_5_0 $site_4_0.tLa40
    set site_5_0 $site_4_0.tLa41
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 603x581+292+128
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1684 1032
    wm minsize $top 126 10
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "GUI" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo38 \
        -width 569 -height 506 -takefocus {} 
    vTcl:DefineAlias "$top.tNo38" "TNotebook1" vTcl:WidgetProc "GUI" 1
    frame .top37.tNo38.pg0 -background #d9d9d9
    $top.tNo38 add .top37.tNo38.pg0 \
        -padding 0 -sticky nsew -state normal -text Seriale -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo38.pg0
    entry $site_4_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable portaSeriale 
    vTcl:DefineAlias "$site_4_0.ent40" "Entry1" vTcl:WidgetProc "GUI" 1
    button $site_4_0.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.apriSeriale \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Usa questa} 
    vTcl:DefineAlias "$site_4_0.but41" "Button1" vTcl:WidgetProc "GUI" 1
    button $site_4_0.but37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.apriFTDI \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Usa FTDI} 
    vTcl:DefineAlias "$site_4_0.but37" "Button47" vTcl:WidgetProc "GUI" 1
    button $site_4_0.but38 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.apriSocket \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text TCP 
    vTcl:DefineAlias "$site_4_0.but38" "Button4" vTcl:WidgetProc "GUI" 1
    entry $site_4_0.cpd39 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable indirizzoIP 
    vTcl:DefineAlias "$site_4_0.cpd39" "Entry4" vTcl:WidgetProc "GUI" 1
    place $site_4_0.ent40 \
        -in $site_4_0 -x 130 -y 110 -width 390 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but41 \
        -in $site_4_0 -x 30 -y 110 -width 80 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but37 \
        -in $site_4_0 -x 30 -y 165 -width 80 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but38 \
        -in $site_4_0 -x 30 -y 215 -width 82 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_4_0.cpd39 \
        -in $site_4_0 -x 130 -y 215 -width 199 -height 25 -anchor nw \
        -bordermode inside 
    frame .top37.tNo38.pg1 -background #d9d9d9
    $top.tNo38 add .top37.tNo38.pg1 \
        -padding 0 -sticky nsew -state normal -text Varie -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo38.pg1
    button $site_4_1.but37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.Eco -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Eco 
    vTcl:DefineAlias "$site_4_1.but37" "Button2" vTcl:WidgetProc "GUI" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_1.tLa37 \
        -text Echi -width 230 -height 210 
    vTcl:DefineAlias "$site_4_1.tLa37" "TLabelframe1" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_1.tLa37
    label $site_5_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Invia 
    vTcl:DefineAlias "$site_5_0.lab39" "Label2" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable numEco 
    vTcl:DefineAlias "$site_5_0.ent40" "Entry2" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Esegui 
    vTcl:DefineAlias "$site_5_0.but41" "Button3" vTcl:WidgetProc "GUI" 1
    bind $site_5_0.but41 <ButtonRelease-1> {
        self.ecoProva
    }
    ttk::progressbar $site_5_0.tPr43 \
        -mode indeterminate 
    vTcl:DefineAlias "$site_5_0.tPr43" "TProgressbar1" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab37 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text pacchetti 
    vTcl:DefineAlias "$site_5_0.lab37" "Label3" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text da 
    vTcl:DefineAlias "$site_5_0.lab38" "Label4" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent39 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable dimEco 
    vTcl:DefineAlias "$site_5_0.ent39" "Entry3" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text byte 
    vTcl:DefineAlias "$site_5_0.lab40" "Label5" vTcl:WidgetProc "GUI" 1
    place $site_5_0.lab39 \
        -in $site_5_0 -x 20 -y 25 -width 39 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent40 \
        -in $site_5_0 -x 75 -y 25 -width 69 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but41 \
        -in $site_5_0 -x 70 -y 115 -width 90 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tPr43 \
        -in $site_5_0 -x 25 -y 160 -width 180 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab37 \
        -in $site_5_0 -x 155 -y 25 -anchor nw -bordermode ignore 
    place $site_5_0.lab38 \
        -in $site_5_0 -x 35 -y 70 -width 29 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent39 \
        -in $site_5_0 -x 75 -y 65 -width 69 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab40 \
        -in $site_5_0 -x 160 -y 70 -anchor nw -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_1.tLa38 \
        -text Aggiorna -width 217 -height 127 
    vTcl:DefineAlias "$site_4_1.tLa38" "TLabelframe10" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_1.tLa38
    button $site_5_0.cpd39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.aggiorna \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Con questo} 
    vTcl:DefineAlias "$site_5_0.cpd39" "Button22" vTcl:WidgetProc "GUI" 1
    ttk::progressbar $site_5_0.cpd40 \
        -variable aggiorna 
    vTcl:DefineAlias "$site_5_0.cpd40" "TProgressbar2" vTcl:WidgetProc "GUI" 1
    place $site_5_0.cpd39 \
        -in $site_5_0 -x 64 -y 9 -width 79 -height 29 -anchor nw \
        -bordermode inside 
    place $site_5_0.cpd40 \
        -in $site_5_0 -x 29 -y 61 -width 153 -height 22 -anchor nw \
        -bordermode inside 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_1.tLa39 \
        -text Versione -width 299 -height 121 
    vTcl:DefineAlias "$site_4_1.tLa39" "TLabelframe11" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_1.tLa39
    entry $site_5_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -insertbackground black -justify center \
        -state readonly -textvariable veri 
    vTcl:DefineAlias "$site_5_0.ent40" "Entry9" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent42 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -insertbackground black -justify center \
        -state readonly -textvariable verd 
    vTcl:DefineAlias "$site_5_0.ent42" "Entry10" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.ver -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Leggi 
    vTcl:DefineAlias "$site_5_0.but43" "Button23" vTcl:WidgetProc "GUI" 1
    place $site_5_0.ent40 \
        -in $site_5_0 -x 124 -y 29 -width 143 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent42 \
        -in $site_5_0 -x 124 -y 68 -width 141 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but43 \
        -in $site_5_0 -x 30 -y 32 -width 60 -height 58 -anchor nw \
        -bordermode ignore 
    place $site_4_1.but37 \
        -in $site_4_1 -x 30 -y 25 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa37 \
        -in $site_4_1 -x 100 -y 10 -width 230 -height 210 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa38 \
        -in $site_4_1 -x 18 -y 250 -width 217 -height 127 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa39 \
        -in $site_4_1 -x 253 -y 253 -width 299 -height 121 -anchor nw \
        -bordermode ignore 
    frame .top37.tNo38.pg2 -background #d9d9d9
    $top.tNo38 add .top37.tNo38.pg2 \
        -padding 0 -sticky nsew -state normal -text Prod -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo38.pg2
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_2.tLa37 \
        -text {Codice prodotto} -width 385 -height 120 
    vTcl:DefineAlias "$site_4_2.tLa37" "TLabelframe2" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_2.tLa37
    entry $site_5_0.ent38 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black -textvariable cp 
    vTcl:DefineAlias "$site_5_0.ent38" "Entry5" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.leggi_cp \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Leggi 
    vTcl:DefineAlias "$site_5_0.but39" "Button5" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.inventa_cp \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Inventa 
    vTcl:DefineAlias "$site_5_0.but41" "Button7" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.scrivi_cp \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Scrivi 
    vTcl:DefineAlias "$site_5_0.but40" "Button6" vTcl:WidgetProc "GUI" 1
    place $site_5_0.ent38 \
        -in $site_5_0 -x 90 -y 30 -width 194 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but39 \
        -in $site_5_0 -x 20 -y 30 -width 55 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but41 \
        -in $site_5_0 -x 155 -y 70 -width 65 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but40 \
        -in $site_5_0 -x 300 -y 30 -width 54 -height 29 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_2.cpd43 \
        -text {Codice scheda} -width 385 -height 120 
    vTcl:DefineAlias "$site_4_2.cpd43" "TLabelframe3" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_2.cpd43
    entry $site_5_0.ent38 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black -textvariable cs 
    vTcl:DefineAlias "$site_5_0.ent38" "Entry6" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.leggi_cs \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Leggi 
    vTcl:DefineAlias "$site_5_0.but39" "Button8" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.inventa_cs \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Inventa 
    vTcl:DefineAlias "$site_5_0.but41" "Button9" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.scrivi_cs \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Scrivi 
    vTcl:DefineAlias "$site_5_0.but40" "Button10" vTcl:WidgetProc "GUI" 1
    place $site_5_0.ent38 \
        -in $site_5_0 -x 90 -y 30 -width 194 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but39 \
        -in $site_5_0 -x 20 -y 30 -width 55 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but41 \
        -in $site_5_0 -x 155 -y 70 -width 65 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but40 \
        -in $site_5_0 -x 300 -y 30 -width 54 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tLa37 \
        -in $site_4_2 -x 20 -y 30 -width 385 -height 120 -anchor nw \
        -bordermode ignore 
    place $site_4_2.cpd43 \
        -in $site_4_2 -x 20 -y 165 -anchor nw -bordermode inside 
    frame .top37.tNo38.pg3 -background #d9d9d9
    $top.tNo38 add .top37.tNo38.pg3 \
        -padding 0 -sticky nsew -state normal -text HW -image {} \
        -compound none -underline -1 
    set site_4_3  $top.tNo38.pg3
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_3.tLa37 \
        -text Tasto -width 285 -height 90 
    vTcl:DefineAlias "$site_4_3.tLa37" "TLabelframe4" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_3.tLa37
    button $site_5_0.but38 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.tst_zero \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Azzera 
    vTcl:DefineAlias "$site_5_0.but38" "Button11" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.tst_lgg \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Leggi 
    vTcl:DefineAlias "$site_5_0.but39" "Button12" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent40 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black -state readonly \
        -textvariable tst 
    vTcl:DefineAlias "$site_5_0.ent40" "Entry7" vTcl:WidgetProc "GUI" 1
    place $site_5_0.but38 \
        -in $site_5_0 -x 30 -y 30 -width 62 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but39 \
        -in $site_5_0 -x 205 -y 35 -width 62 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent40 \
        -in $site_5_0 -x 110 -y 35 -width 79 -height 25 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_3.tLa38 \
        -text {Cavo in RJ45} -width 210 -height 90 
    vTcl:DefineAlias "$site_4_3.tLa38" "TLabelframe5" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_3.tLa38
    checkbutton $site_5_0.che39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -state disabled -text presente \
        -variable cavo 
    vTcl:DefineAlias "$site_5_0.che39" "Checkbutton1" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.cavo \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Leggi 
    vTcl:DefineAlias "$site_5_0.but40" "Button13" vTcl:WidgetProc "GUI" 1
    place $site_5_0.che39 \
        -in $site_5_0 -x 25 -y 35 -anchor nw -bordermode ignore 
    place $site_5_0.but40 \
        -in $site_5_0 -x 125 -y 30 -width 65 -height 34 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_3.tLa39 \
        -text Flussi -width 370 -height 100 
    vTcl:DefineAlias "$site_4_3.tLa39" "TLabelframe6" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_3.tLa39
    button $site_5_0.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.mobd \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {MOBD ->} 
    vTcl:DefineAlias "$site_5_0.but40" "Button14" vTcl:WidgetProc "GUI" 1
    radiobutton $site_5_0.rad41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text FOBD -value 0 \
        -variable io33 
    vTcl:DefineAlias "$site_5_0.rad41" "Radiobutton1" vTcl:WidgetProc "GUI" 1
    radiobutton $site_5_0.cpd42 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text ETH -value 1 -variable io33 
    vTcl:DefineAlias "$site_5_0.cpd42" "Radiobutton2" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.eth -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {ETH ->} 
    vTcl:DefineAlias "$site_5_0.but43" "Button15" vTcl:WidgetProc "GUI" 1
    radiobutton $site_5_0.rad44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text RJ45 -value 0 -variable io5 
    vTcl:DefineAlias "$site_5_0.rad44" "Radiobutton3" vTcl:WidgetProc "GUI" 1
    radiobutton $site_5_0.cpd45 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text esp32 -value 1 \
        -variable io5 
    vTcl:DefineAlias "$site_5_0.cpd45" "Radiobutton4" vTcl:WidgetProc "GUI" 1
    place $site_5_0.but40 \
        -in $site_5_0 -x 30 -y 40 -width 67 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.rad41 \
        -in $site_5_0 -x 110 -y 25 -anchor nw -bordermode ignore 
    place $site_5_0.cpd42 \
        -in $site_5_0 -x 110 -y 40 -anchor nw -bordermode inside 
    place $site_5_0.but43 \
        -in $site_5_0 -x 190 -y 40 -width 57 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.rad44 \
        -in $site_5_0 -x 270 -y 25 -anchor nw -bordermode ignore 
    place $site_5_0.cpd45 \
        -in $site_5_0 -x 270 -y 40 -anchor nw -bordermode inside 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_3.tLa46 \
        -text Led -width 138 -height 182 
    vTcl:DefineAlias "$site_4_3.tLa46" "TLabelframe7" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_3.tLa46
    radiobutton $site_5_0.rad47 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Verde -value 0 \
        -variable led 
    vTcl:DefineAlias "$site_5_0.rad47" "Radiobutton5" vTcl:WidgetProc "GUI" 1
    radiobutton $site_5_0.cpd48 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Rosso -value 1 \
        -variable led 
    vTcl:DefineAlias "$site_5_0.cpd48" "Radiobutton6" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but49 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.led -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Scrivi 
    vTcl:DefineAlias "$site_5_0.but49" "Button16" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.ledr \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Ripetutamente 
    vTcl:DefineAlias "$site_5_0.but37" "Button21" vTcl:WidgetProc "GUI" 1
    place $site_5_0.rad47 \
        -in $site_5_0 -x 30 -y 25 -anchor nw -bordermode ignore 
    place $site_5_0.cpd48 \
        -in $site_5_0 -x 30 -y 35 -anchor nw -bordermode inside 
    place $site_5_0.but49 \
        -in $site_5_0 -x 30 -y 85 -width 67 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but37 \
        -in $site_5_0 -x 19 -y 130 -width 99 -height 32 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_3.tLa40 \
        -text {Rileva diagnosi} -width 415 -height 90 
    vTcl:DefineAlias "$site_4_3.tLa40" "TLabelframe8" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_3.tLa40
    button $site_5_0.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.rid_ini \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Inizia 
    vTcl:DefineAlias "$site_5_0.but41" "Button17" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but42 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.rid_fin \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Termina 
    vTcl:DefineAlias "$site_5_0.but42" "Button18" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.rid_esi \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Esito 
    vTcl:DefineAlias "$site_5_0.but43" "Button19" vTcl:WidgetProc "GUI" 1
    checkbutton $site_5_0.che44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -state disabled -text DoIP \
        -variable doip 
    vTcl:DefineAlias "$site_5_0.che44" "Checkbutton2" vTcl:WidgetProc "GUI" 1
    place $site_5_0.but41 \
        -in $site_5_0 -x 30 -y 30 -width 68 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but42 \
        -in $site_5_0 -x 125 -y 30 -width 70 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but43 \
        -in $site_5_0 -x 230 -y 30 -width 71 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.che44 \
        -in $site_5_0 -x 320 -y 30 -anchor nw -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_3.tLa41 \
        -text PHY -width 315 -height 75 
    vTcl:DefineAlias "$site_4_3.tLa41" "TLabelframe9" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_3.tLa41
    label $site_5_0.lab42 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Impulso di} 
    vTcl:DefineAlias "$site_5_0.lab42" "Label6" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent43 \
        -background white -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable phy_ms 
    vTcl:DefineAlias "$site_5_0.ent43" "Entry8" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text ms 
    vTcl:DefineAlias "$site_5_0.lab44" "Label7" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but45 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.phy_reset \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Resetta 
    vTcl:DefineAlias "$site_5_0.but45" "Button20" vTcl:WidgetProc "GUI" 1
    place $site_5_0.lab42 \
        -in $site_5_0 -x 15 -y 30 -width 67 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent43 \
        -in $site_5_0 -x 95 -y 30 -width 59 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab44 \
        -in $site_5_0 -x 165 -y 30 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but45 \
        -in $site_5_0 -x 215 -y 25 -width 72 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_4_3.tLa37 \
        -in $site_4_3 -x 20 -y 20 -width 285 -height 90 -anchor nw \
        -bordermode ignore 
    place $site_4_3.tLa38 \
        -in $site_4_3 -x 325 -y 20 -width 210 -height 90 -anchor nw \
        -bordermode ignore 
    place $site_4_3.tLa39 \
        -in $site_4_3 -x 20 -y 125 -width 370 -height 100 -anchor nw \
        -bordermode ignore 
    place $site_4_3.tLa46 \
        -in $site_4_3 -x 410 -y 130 -width 138 -height 182 -anchor nw \
        -bordermode ignore 
    place $site_4_3.tLa40 \
        -in $site_4_3 -x 25 -y 320 -width 415 -height 90 -anchor nw \
        -bordermode ignore 
    place $site_4_3.tLa41 \
        -in $site_4_3 -x 25 -y 230 -width 315 -height 75 -anchor nw \
        -bordermode ignore 
    label $top.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -textvariable Messaggio 
    vTcl:DefineAlias "$top.lab39" "Label1" vTcl:WidgetProc "GUI" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo38 \
        -in $top -x 15 -y 45 -width 569 -height 506 -anchor nw \
        -bordermode ignore 
    place $top.lab39 \
        -in $top -x 20 -y 10 -width 559 -height 21 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

