#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Aug 02, 2018 12:28:06 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('New_Toplevel_1')
    geom = "603x581+292+128"
    root.geometry(geom)
    gui_support.set_Tk_var()
    w = New_Toplevel_1 (root)
    gui_support.init(root, w)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('New_Toplevel_1')
    geom = "603x581+292+128"
    w.geometry(geom)
    gui_support.set_Tk_var()
    w_win = New_Toplevel_1 (w)
    gui_support.init(w, w_win, param)
    return w_win

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font11 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        master.configure(background="#d9d9d9")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")


        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(master)
        self.TNotebook1.place(relx=0.02, rely=0.08, relheight=0.87
                , relwidth=0.94)
        self.TNotebook1.configure(width=569)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_pg0 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_pg0, padding=3)
        self.TNotebook1.tab(0, text="Seriale",underline="-1",)
        self.TNotebook1_pg1 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_pg1, padding=3)
        self.TNotebook1.tab(1, text="Varie",underline="-1",)
        self.TNotebook1_pg2 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_pg2, padding=3)
        self.TNotebook1.tab(2, text="Prod",underline="-1",)
        self.TNotebook1_pg3 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_pg3, padding=3)
        self.TNotebook1.tab(3, text="HW",underline="-1",)

        self.Entry1 = Entry(self.TNotebook1_pg0)
        self.Entry1.place(relx=0.23, rely=0.23, relheight=0.05, relwidth=0.69)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font=font11)
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(justify=CENTER)
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvariable=gui_support.portaSeriale)

        self.Button1 = Button(self.TNotebook1_pg0)
        self.Button1.place(relx=0.05, rely=0.23, height=25, width=80)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background=_bgcolor)
        self.Button1.configure(command=self.apriSeriale)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Usa questa''')

        self.Button47 = Button(self.TNotebook1_pg0)
        self.Button47.place(relx=0.05, rely=0.34, height=25, width=80)
        self.Button47.configure(activebackground="#d9d9d9")
        self.Button47.configure(activeforeground="#000000")
        self.Button47.configure(background=_bgcolor)
        self.Button47.configure(command=self.apriFTDI)
        self.Button47.configure(disabledforeground="#a3a3a3")
        self.Button47.configure(foreground="#000000")
        self.Button47.configure(highlightbackground="#d9d9d9")
        self.Button47.configure(highlightcolor="black")
        self.Button47.configure(pady="0")
        self.Button47.configure(text='''Usa FTDI''')

        self.Button4 = Button(self.TNotebook1_pg0)
        self.Button4.place(relx=0.05, rely=0.45, height=24, width=82)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background=_bgcolor)
        self.Button4.configure(command=self.apriSocket)
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''TCP''')

        self.Entry4 = Entry(self.TNotebook1_pg0)
        self.Entry4.place(relx=0.23, rely=0.45, relheight=0.05, relwidth=0.35)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font=font11)
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(justify=CENTER)
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")
        self.Entry4.configure(textvariable=gui_support.indirizzoIP)

        self.Button2 = Button(self.TNotebook1_pg1)
        self.Button2.place(relx=0.05, rely=0.05, height=25, width=50)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background=_bgcolor)
        self.Button2.configure(command=self.Eco)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Eco''')

        self.TLabelframe1 = ttk.Labelframe(self.TNotebook1_pg1)
        self.TLabelframe1.place(relx=0.18, rely=0.02, relheight=0.44
                , relwidth=0.41)
        self.TLabelframe1.configure(text='''Echi''')
        self.TLabelframe1.configure(width=230)

        self.Label2 = Label(self.TLabelframe1)
        self.Label2.place(relx=0.09, rely=0.12, height=25, width=39)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background=_bgcolor)
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Invia''')

        self.Entry2 = Entry(self.TLabelframe1)
        self.Entry2.place(relx=0.33, rely=0.12, relheight=0.12, relwidth=0.3)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font=font11)
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(justify=CENTER)
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(textvariable=gui_support.numEco)

        self.Button3 = Button(self.TLabelframe1)
        self.Button3.place(relx=0.3, rely=0.55, height=25, width=90)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background=_bgcolor)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Esegui''')
        self.Button3.bind('<ButtonRelease-1>',self.ecoProva)

        self.TProgressbar1 = ttk.Progressbar(self.TLabelframe1)
        self.TProgressbar1.place(relx=0.11, rely=0.76, relwidth=0.78
                , relheight=0.0, height=22)
        self.TProgressbar1.configure(mode="indeterminate")

        self.Label3 = Label(self.TLabelframe1)
        self.Label3.place(relx=0.67, rely=0.12, height=21, width=55)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background=_bgcolor)
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''pacchetti''')

        self.Label4 = Label(self.TLabelframe1)
        self.Label4.place(relx=0.15, rely=0.33, height=21, width=29)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background=_bgcolor)
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''da''')

        self.Entry3 = Entry(self.TLabelframe1)
        self.Entry3.place(relx=0.33, rely=0.31, relheight=0.12, relwidth=0.3)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font=font11)
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(justify=CENTER)
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")
        self.Entry3.configure(textvariable=gui_support.dimEco)

        self.Label5 = Label(self.TLabelframe1)
        self.Label5.place(relx=0.7, rely=0.33, height=21, width=29)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background=_bgcolor)
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''byte''')

        self.TLabelframe10 = ttk.Labelframe(self.TNotebook1_pg1)
        self.TLabelframe10.place(relx=0.03, rely=0.52, relheight=0.26
                , relwidth=0.38)
        self.TLabelframe10.configure(text='''Aggiorna''')
        self.TLabelframe10.configure(width=217)

        self.Button22 = Button(self.TLabelframe10)
        self.Button22.place(relx=0.3, rely=0.2, height=29, width=79)
        self.Button22.configure(activebackground="#d9d9d9")
        self.Button22.configure(activeforeground="#000000")
        self.Button22.configure(background=_bgcolor)
        self.Button22.configure(command=self.aggiorna)
        self.Button22.configure(disabledforeground="#a3a3a3")
        self.Button22.configure(foreground="#000000")
        self.Button22.configure(highlightbackground="#d9d9d9")
        self.Button22.configure(highlightcolor="black")
        self.Button22.configure(pady="0")
        self.Button22.configure(text='''Con questo''')

        self.TProgressbar2 = ttk.Progressbar(self.TLabelframe10)
        self.TProgressbar2.place(relx=0.14, rely=0.61, relwidth=0.71
                , relheight=0.0, height=22)
        self.TProgressbar2.configure(variable=gui_support.aggiorna)

        self.TLabelframe11 = ttk.Labelframe(self.TNotebook1_pg1)
        self.TLabelframe11.place(relx=0.44, rely=0.53, relheight=0.25
                , relwidth=0.53)
        self.TLabelframe11.configure(text='''Versione''')
        self.TLabelframe11.configure(width=299)

        self.Entry9 = Entry(self.TLabelframe11)
        self.Entry9.place(relx=0.4, rely=0.24, relheight=0.19, relwidth=0.48)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font=font11)
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(insertbackground="black")
        self.Entry9.configure(justify=CENTER)
        READONLY = 'readonly'
        self.Entry9.configure(state=READONLY)
        self.Entry9.configure(textvariable=gui_support.veri)
        self.Entry9.configure(width=143)

        self.Entry10 = Entry(self.TLabelframe11)
        self.Entry10.place(relx=0.4, rely=0.56, relheight=0.19, relwidth=0.47)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font=font11)
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(insertbackground="black")
        self.Entry10.configure(justify=CENTER)
        READONLY = 'readonly'
        self.Entry10.configure(state=READONLY)
        self.Entry10.configure(textvariable=gui_support.verd)
        self.Entry10.configure(width=141)

        self.Button23 = Button(self.TLabelframe11)
        self.Button23.place(relx=0.1, rely=0.26, height=58, width=60)
        self.Button23.configure(activebackground="#d9d9d9")
        self.Button23.configure(activeforeground="#000000")
        self.Button23.configure(background=_bgcolor)
        self.Button23.configure(command=self.ver)
        self.Button23.configure(disabledforeground="#a3a3a3")
        self.Button23.configure(foreground="#000000")
        self.Button23.configure(highlightbackground="#d9d9d9")
        self.Button23.configure(highlightcolor="black")
        self.Button23.configure(pady="0")
        self.Button23.configure(text='''Leggi''')
        self.Button23.configure(width=60)

        self.TLabelframe2 = ttk.Labelframe(self.TNotebook1_pg2)
        self.TLabelframe2.place(relx=0.04, rely=0.06, relheight=0.24
                , relwidth=0.68)
        self.TLabelframe2.configure(text='''Codice prodotto''')
        self.TLabelframe2.configure(width=385)

        self.Entry5 = Entry(self.TLabelframe2)
        self.Entry5.place(relx=0.23, rely=0.25, relheight=0.21, relwidth=0.5)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font=font11)
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(justify=CENTER)
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")
        self.Entry5.configure(textvariable=gui_support.cp)

        self.Button5 = Button(self.TLabelframe2)
        self.Button5.place(relx=0.05, rely=0.25, height=29, width=55)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background=_bgcolor)
        self.Button5.configure(command=self.leggi_cp)
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Leggi''')

        self.Button7 = Button(self.TLabelframe2)
        self.Button7.place(relx=0.4, rely=0.58, height=29, width=65)
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background=_bgcolor)
        self.Button7.configure(command=self.inventa_cp)
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(text='''Inventa''')

        self.Button6 = Button(self.TLabelframe2)
        self.Button6.place(relx=0.78, rely=0.25, height=29, width=54)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background=_bgcolor)
        self.Button6.configure(command=self.scrivi_cp)
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''Scrivi''')

        self.TLabelframe3 = ttk.Labelframe(self.TNotebook1_pg2)
        self.TLabelframe3.place(relx=0.04, rely=0.33, relheight=0.24
                , relwidth=0.68)
        self.TLabelframe3.configure(text='''Codice scheda''')
        self.TLabelframe3.configure(width=385)

        self.Entry6 = Entry(self.TLabelframe3)
        self.Entry6.place(relx=0.23, rely=0.25, relheight=0.21, relwidth=0.5)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font=font11)
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(justify=CENTER)
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")
        self.Entry6.configure(textvariable=gui_support.cs)

        self.Button8 = Button(self.TLabelframe3)
        self.Button8.place(relx=0.05, rely=0.25, height=29, width=55)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background=_bgcolor)
        self.Button8.configure(command=self.leggi_cs)
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(text='''Leggi''')

        self.Button9 = Button(self.TLabelframe3)
        self.Button9.place(relx=0.4, rely=0.58, height=29, width=65)
        self.Button9.configure(activebackground="#d9d9d9")
        self.Button9.configure(activeforeground="#000000")
        self.Button9.configure(background=_bgcolor)
        self.Button9.configure(command=self.inventa_cs)
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0")
        self.Button9.configure(text='''Inventa''')

        self.Button10 = Button(self.TLabelframe3)
        self.Button10.place(relx=0.78, rely=0.25, height=29, width=54)
        self.Button10.configure(activebackground="#d9d9d9")
        self.Button10.configure(activeforeground="#000000")
        self.Button10.configure(background=_bgcolor)
        self.Button10.configure(command=self.scrivi_cs)
        self.Button10.configure(disabledforeground="#a3a3a3")
        self.Button10.configure(foreground="#000000")
        self.Button10.configure(highlightbackground="#d9d9d9")
        self.Button10.configure(highlightcolor="black")
        self.Button10.configure(pady="0")
        self.Button10.configure(text='''Scrivi''')

        self.TLabelframe4 = ttk.Labelframe(self.TNotebook1_pg3)
        self.TLabelframe4.place(relx=0.04, rely=0.04, relheight=0.18
                , relwidth=0.5)
        self.TLabelframe4.configure(text='''Tasto''')
        self.TLabelframe4.configure(width=285)

        self.Button11 = Button(self.TLabelframe4)
        self.Button11.place(relx=0.11, rely=0.33, height=34, width=62)
        self.Button11.configure(activebackground="#d9d9d9")
        self.Button11.configure(activeforeground="#000000")
        self.Button11.configure(background=_bgcolor)
        self.Button11.configure(command=self.tst_zero)
        self.Button11.configure(disabledforeground="#a3a3a3")
        self.Button11.configure(foreground="#000000")
        self.Button11.configure(highlightbackground="#d9d9d9")
        self.Button11.configure(highlightcolor="black")
        self.Button11.configure(pady="0")
        self.Button11.configure(text='''Azzera''')

        self.Button12 = Button(self.TLabelframe4)
        self.Button12.place(relx=0.72, rely=0.39, height=29, width=62)
        self.Button12.configure(activebackground="#d9d9d9")
        self.Button12.configure(activeforeground="#000000")
        self.Button12.configure(background=_bgcolor)
        self.Button12.configure(command=self.tst_lgg)
        self.Button12.configure(disabledforeground="#a3a3a3")
        self.Button12.configure(foreground="#000000")
        self.Button12.configure(highlightbackground="#d9d9d9")
        self.Button12.configure(highlightcolor="black")
        self.Button12.configure(pady="0")
        self.Button12.configure(text='''Leggi''')

        self.Entry7 = Entry(self.TLabelframe4)
        self.Entry7.place(relx=0.39, rely=0.39, relheight=0.28, relwidth=0.28)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font=font11)
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(justify=CENTER)
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")
        READONLY = 'readonly'
        self.Entry7.configure(state=READONLY)
        self.Entry7.configure(textvariable=gui_support.tst)

        self.TLabelframe5 = ttk.Labelframe(self.TNotebook1_pg3)
        self.TLabelframe5.place(relx=0.57, rely=0.04, relheight=0.18
                , relwidth=0.37)
        self.TLabelframe5.configure(text='''Cavo in RJ45''')
        self.TLabelframe5.configure(width=210)

        self.Checkbutton1 = Checkbutton(self.TLabelframe5)
        self.Checkbutton1.place(relx=0.12, rely=0.39, relheight=0.28
                , relwidth=0.35)
        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(background=_bgcolor)
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify=LEFT)
        self.Checkbutton1.configure(state=DISABLED)
        self.Checkbutton1.configure(text='''presente''')
        self.Checkbutton1.configure(variable=gui_support.cavo)

        self.Button13 = Button(self.TLabelframe5)
        self.Button13.place(relx=0.6, rely=0.33, height=34, width=65)
        self.Button13.configure(activebackground="#d9d9d9")
        self.Button13.configure(activeforeground="#000000")
        self.Button13.configure(background=_bgcolor)
        self.Button13.configure(command=self.cavo)
        self.Button13.configure(disabledforeground="#a3a3a3")
        self.Button13.configure(foreground="#000000")
        self.Button13.configure(highlightbackground="#d9d9d9")
        self.Button13.configure(highlightcolor="black")
        self.Button13.configure(pady="0")
        self.Button13.configure(text='''Leggi''')

        self.TLabelframe6 = ttk.Labelframe(self.TNotebook1_pg3)
        self.TLabelframe6.place(relx=0.04, rely=0.25, relheight=0.2
                , relwidth=0.65)
        self.TLabelframe6.configure(text='''Flussi''')
        self.TLabelframe6.configure(width=370)

        self.Button14 = Button(self.TLabelframe6)
        self.Button14.place(relx=0.08, rely=0.4, height=29, width=67)
        self.Button14.configure(activebackground="#d9d9d9")
        self.Button14.configure(activeforeground="#000000")
        self.Button14.configure(background=_bgcolor)
        self.Button14.configure(command=self.mobd)
        self.Button14.configure(disabledforeground="#a3a3a3")
        self.Button14.configure(foreground="#000000")
        self.Button14.configure(highlightbackground="#d9d9d9")
        self.Button14.configure(highlightcolor="black")
        self.Button14.configure(pady="0")
        self.Button14.configure(text='''MOBD ->''')

        self.Radiobutton1 = Radiobutton(self.TLabelframe6)
        self.Radiobutton1.place(relx=0.3, rely=0.25, relheight=0.25
                , relwidth=0.16)
        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background=_bgcolor)
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify=LEFT)
        self.Radiobutton1.configure(text='''FOBD''')
        self.Radiobutton1.configure(value="0")
        self.Radiobutton1.configure(variable=gui_support.io33)

        self.Radiobutton2 = Radiobutton(self.TLabelframe6)
        self.Radiobutton2.place(relx=0.3, rely=0.57, relheight=0.25
                , relwidth=0.14)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background=_bgcolor)
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify=LEFT)
        self.Radiobutton2.configure(text='''ETH''')
        self.Radiobutton2.configure(value="1")
        self.Radiobutton2.configure(variable=gui_support.io33)

        self.Button15 = Button(self.TLabelframe6)
        self.Button15.place(relx=0.51, rely=0.4, height=29, width=57)
        self.Button15.configure(activebackground="#d9d9d9")
        self.Button15.configure(activeforeground="#000000")
        self.Button15.configure(background=_bgcolor)
        self.Button15.configure(command=self.eth)
        self.Button15.configure(disabledforeground="#a3a3a3")
        self.Button15.configure(foreground="#000000")
        self.Button15.configure(highlightbackground="#d9d9d9")
        self.Button15.configure(highlightcolor="black")
        self.Button15.configure(pady="0")
        self.Button15.configure(text='''ETH ->''')

        self.Radiobutton3 = Radiobutton(self.TLabelframe6)
        self.Radiobutton3.place(relx=0.73, rely=0.25, relheight=0.25
                , relwidth=0.14)
        self.Radiobutton3.configure(activebackground="#d9d9d9")
        self.Radiobutton3.configure(activeforeground="#000000")
        self.Radiobutton3.configure(background=_bgcolor)
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(justify=LEFT)
        self.Radiobutton3.configure(text='''RJ45''')
        self.Radiobutton3.configure(value="0")
        self.Radiobutton3.configure(variable=gui_support.io5)

        self.Radiobutton4 = Radiobutton(self.TLabelframe6)
        self.Radiobutton4.place(relx=0.73, rely=0.57, relheight=0.25
                , relwidth=0.16)
        self.Radiobutton4.configure(activebackground="#d9d9d9")
        self.Radiobutton4.configure(activeforeground="#000000")
        self.Radiobutton4.configure(background=_bgcolor)
        self.Radiobutton4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton4.configure(foreground="#000000")
        self.Radiobutton4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton4.configure(highlightcolor="black")
        self.Radiobutton4.configure(justify=LEFT)
        self.Radiobutton4.configure(text='''esp32''')
        self.Radiobutton4.configure(value="1")
        self.Radiobutton4.configure(variable=gui_support.io5)

        self.TLabelframe7 = ttk.Labelframe(self.TNotebook1_pg3)
        self.TLabelframe7.place(relx=0.72, rely=0.26, relheight=0.36
                , relwidth=0.24)
        self.TLabelframe7.configure(text='''Led''')
        self.TLabelframe7.configure(width=138)

        self.Radiobutton5 = Radiobutton(self.TLabelframe7)
        self.Radiobutton5.place(relx=0.22, rely=0.14, relheight=0.14
                , relwidth=0.42)
        self.Radiobutton5.configure(activebackground="#d9d9d9")
        self.Radiobutton5.configure(activeforeground="#000000")
        self.Radiobutton5.configure(background=_bgcolor)
        self.Radiobutton5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton5.configure(foreground="#000000")
        self.Radiobutton5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton5.configure(highlightcolor="black")
        self.Radiobutton5.configure(justify=LEFT)
        self.Radiobutton5.configure(text='''Verde''')
        self.Radiobutton5.configure(value="0")
        self.Radiobutton5.configure(variable=gui_support.led)

        self.Radiobutton6 = Radiobutton(self.TLabelframe7)
        self.Radiobutton6.place(relx=0.22, rely=0.29, relheight=0.14
                , relwidth=0.43)
        self.Radiobutton6.configure(activebackground="#d9d9d9")
        self.Radiobutton6.configure(activeforeground="#000000")
        self.Radiobutton6.configure(background=_bgcolor)
        self.Radiobutton6.configure(disabledforeground="#a3a3a3")
        self.Radiobutton6.configure(foreground="#000000")
        self.Radiobutton6.configure(highlightbackground="#d9d9d9")
        self.Radiobutton6.configure(highlightcolor="black")
        self.Radiobutton6.configure(justify=LEFT)
        self.Radiobutton6.configure(text='''Rosso''')
        self.Radiobutton6.configure(value="1")
        self.Radiobutton6.configure(variable=gui_support.led)

        self.Button16 = Button(self.TLabelframe7)
        self.Button16.place(relx=0.22, rely=0.47, height=29, width=67)
        self.Button16.configure(activebackground="#d9d9d9")
        self.Button16.configure(activeforeground="#000000")
        self.Button16.configure(background=_bgcolor)
        self.Button16.configure(command=self.led)
        self.Button16.configure(disabledforeground="#a3a3a3")
        self.Button16.configure(foreground="#000000")
        self.Button16.configure(highlightbackground="#d9d9d9")
        self.Button16.configure(highlightcolor="black")
        self.Button16.configure(pady="0")
        self.Button16.configure(text='''Scrivi''')

        self.Button21 = Button(self.TLabelframe7)
        self.Button21.place(relx=0.11, rely=0.71, height=32, width=99)
        self.Button21.configure(activebackground="#d9d9d9")
        self.Button21.configure(activeforeground="#000000")
        self.Button21.configure(background=_bgcolor)
        self.Button21.configure(command=self.ledr)
        self.Button21.configure(disabledforeground="#a3a3a3")
        self.Button21.configure(foreground="#000000")
        self.Button21.configure(highlightbackground="#d9d9d9")
        self.Button21.configure(highlightcolor="black")
        self.Button21.configure(pady="0")
        self.Button21.configure(text='''Ripetutamente''')

        self.TLabelframe8 = ttk.Labelframe(self.TNotebook1_pg3)
        self.TLabelframe8.place(relx=0.04, rely=0.63, relheight=0.18
                , relwidth=0.73)
        self.TLabelframe8.configure(text='''Rileva diagnosi''')
        self.TLabelframe8.configure(width=415)

        self.Button17 = Button(self.TLabelframe8)
        self.Button17.place(relx=0.07, rely=0.33, height=29, width=68)
        self.Button17.configure(activebackground="#d9d9d9")
        self.Button17.configure(activeforeground="#000000")
        self.Button17.configure(background=_bgcolor)
        self.Button17.configure(command=self.rid_ini)
        self.Button17.configure(disabledforeground="#a3a3a3")
        self.Button17.configure(foreground="#000000")
        self.Button17.configure(highlightbackground="#d9d9d9")
        self.Button17.configure(highlightcolor="black")
        self.Button17.configure(pady="0")
        self.Button17.configure(text='''Inizia''')

        self.Button18 = Button(self.TLabelframe8)
        self.Button18.place(relx=0.3, rely=0.33, height=29, width=70)
        self.Button18.configure(activebackground="#d9d9d9")
        self.Button18.configure(activeforeground="#000000")
        self.Button18.configure(background=_bgcolor)
        self.Button18.configure(command=self.rid_fin)
        self.Button18.configure(disabledforeground="#a3a3a3")
        self.Button18.configure(foreground="#000000")
        self.Button18.configure(highlightbackground="#d9d9d9")
        self.Button18.configure(highlightcolor="black")
        self.Button18.configure(pady="0")
        self.Button18.configure(text='''Termina''')

        self.Button19 = Button(self.TLabelframe8)
        self.Button19.place(relx=0.55, rely=0.33, height=29, width=71)
        self.Button19.configure(activebackground="#d9d9d9")
        self.Button19.configure(activeforeground="#000000")
        self.Button19.configure(background=_bgcolor)
        self.Button19.configure(command=self.rid_esi)
        self.Button19.configure(disabledforeground="#a3a3a3")
        self.Button19.configure(foreground="#000000")
        self.Button19.configure(highlightbackground="#d9d9d9")
        self.Button19.configure(highlightcolor="black")
        self.Button19.configure(pady="0")
        self.Button19.configure(text='''Esito''')

        self.Checkbutton2 = Checkbutton(self.TLabelframe8)
        self.Checkbutton2.place(relx=0.77, rely=0.33, relheight=0.28
                , relwidth=0.13)
        self.Checkbutton2.configure(activebackground="#d9d9d9")
        self.Checkbutton2.configure(activeforeground="#000000")
        self.Checkbutton2.configure(background=_bgcolor)
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(foreground="#000000")
        self.Checkbutton2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton2.configure(highlightcolor="black")
        self.Checkbutton2.configure(justify=LEFT)
        self.Checkbutton2.configure(state=DISABLED)
        self.Checkbutton2.configure(text='''DoIP''')
        self.Checkbutton2.configure(variable=gui_support.doip)

        self.TLabelframe9 = ttk.Labelframe(self.TNotebook1_pg3)
        self.TLabelframe9.place(relx=0.04, rely=0.45, relheight=0.15
                , relwidth=0.55)
        self.TLabelframe9.configure(text='''PHY''')
        self.TLabelframe9.configure(width=315)

        self.Label6 = Label(self.TLabelframe9)
        self.Label6.place(relx=0.05, rely=0.4, height=21, width=67)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background=_bgcolor)
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Impulso di''')

        self.Entry8 = Entry(self.TLabelframe9)
        self.Entry8.place(relx=0.3, rely=0.4, relheight=0.33, relwidth=0.19)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font=font11)
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(highlightbackground="#d9d9d9")
        self.Entry8.configure(highlightcolor="black")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(justify=CENTER)
        self.Entry8.configure(selectbackground="#c4c4c4")
        self.Entry8.configure(selectforeground="black")
        self.Entry8.configure(textvariable=gui_support.phy_ms)

        self.Label7 = Label(self.TLabelframe9)
        self.Label7.place(relx=0.52, rely=0.4, height=21, width=34)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background=_bgcolor)
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''ms''')

        self.Button20 = Button(self.TLabelframe9)
        self.Button20.place(relx=0.68, rely=0.33, height=29, width=72)
        self.Button20.configure(activebackground="#d9d9d9")
        self.Button20.configure(activeforeground="#000000")
        self.Button20.configure(background=_bgcolor)
        self.Button20.configure(command=self.phy_reset)
        self.Button20.configure(disabledforeground="#a3a3a3")
        self.Button20.configure(foreground="#000000")
        self.Button20.configure(highlightbackground="#d9d9d9")
        self.Button20.configure(highlightcolor="black")
        self.Button20.configure(pady="0")
        self.Button20.configure(text='''Resetta''')

        self.Label1 = Label(master)
        self.Label1.place(relx=0.03, rely=0.02, height=21, width=559)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background=_bgcolor)
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(textvariable=gui_support.Messaggio)



    def Eco(self):
            print('self.Eco')
            sys.stdout.flush()

    def aggiorna(self):
            print('self.aggiorna')
            sys.stdout.flush()

    def apriFTDI(self):
            print('self.apriFTDI')
            sys.stdout.flush()

    def apriSeriale(self):
            print('self.apriSeriale')
            sys.stdout.flush()

    def apriSocket(self):
            print('self.apriSocket')
            sys.stdout.flush()

    def cavo(self):
            print('self.cavo')
            sys.stdout.flush()

    def ecoProva(self,p1):
            print('self.ecoProva')
            sys.stdout.flush()

    def eth(self):
            print('self.eth')
            sys.stdout.flush()

    def inventa_cp(self):
            print('self.inventa_cp')
            sys.stdout.flush()

    def inventa_cs(self):
            print('self.inventa_cs')
            sys.stdout.flush()

    def led(self):
            print('self.led')
            sys.stdout.flush()

    def ledr(self):
            print('self.ledr')
            sys.stdout.flush()

    def leggi_cp(self):
            print('self.leggi_cp')
            sys.stdout.flush()

    def leggi_cs(self):
            print('self.leggi_cs')
            sys.stdout.flush()

    def mobd(self):
            print('self.mobd')
            sys.stdout.flush()

    def phy_reset(self):
            print('self.phy_reset')
            sys.stdout.flush()

    def rid_esi(self):
            print('self.rid_esi')
            sys.stdout.flush()

    def rid_fin(self):
            print('self.rid_fin')
            sys.stdout.flush()

    def rid_ini(self):
            print('self.rid_ini')
            sys.stdout.flush()

    def scrivi_cp(self):
            print('self.scrivi_cp')
            sys.stdout.flush()

    def scrivi_cs(self):
            print('self.scrivi_cs')
            sys.stdout.flush()

    def tst_lgg(self):
            print('self.tst_lgg')
            sys.stdout.flush()

    def tst_zero(self):
            print('self.tst_zero')
            sys.stdout.flush()

    def ver(self):
            print('self.ver')
            sys.stdout.flush()





if __name__ == '__main__':
    vp_start_gui()



