#! /usr/bin/env python
#
# Support module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Aug 02, 2018 12:27:59 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global portaSeriale
    portaSeriale = StringVar()

    global indirizzoIP
    indirizzoIP = StringVar()

    global numEco
    numEco = StringVar()

    global dimEco
    dimEco = StringVar()

    global aggiorna
    aggiorna = IntVar()

    global veri
    veri = StringVar()

    global verd
    verd = StringVar()

    global cp
    cp = StringVar()

    global cs
    cs = StringVar()

    global tst
    tst = StringVar()

    global cavo
    cavo = StringVar()

    global io33
    io33 = StringVar()

    global io5
    io5 = StringVar()

    global led
    led = StringVar()

    global doip
    doip = StringVar()

    global phy_ms
    phy_ms = StringVar()

    global Messaggio
    Messaggio = StringVar()


def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


